# Elastix parameter file: B-spline registration (grid spacing 40)
(FixedInternalImagePixelType "float")
(MovingInternalImagePixelType "float")
(FixedImageDimension 2)
(MovingImageDimension 2)
(Registration "MultiResolutionRegistration")
(NumberOfResolutions 4)
(MaximumNumberOfIterations 2000)
(NumberOfSamplesForExactGradient 100000)
(AutomaticParameterEstimation "true")
(Metric "AdvancedMattesMutualInformation")
(Optimizer "AdaptiveStochasticGradientDescent")
(Transform "BSplineTransform")
(BSplineTransformSplineOrder 3)
(NumberOfSpatialSamples 2048)
(Interpolator "BSplineInterpolator")
(ResampleInterpolator "FinalBSplineInterpolator")
(Resampler "DefaultResampler")
(DefaultPixelValue 0)
(FinalGridSpacingInPhysicalUnits 40.0)
