# Elastix parameter file: rigid registration
(FixedInternalImagePixelType "float")
(MovingInternalImagePixelType "float")
(FixedImageDimension 2)
(MovingImageDimension 2)
(Registration "MultiResolutionRegistration")
(NumberOfResolutions 4)
(MaximumNumberOfIterations 200)
(NumberOfSamplesForExactGradient 100000)
(AutomaticParameterEstimation "true")
(Metric "AdvancedMattesMutualInformation")
(Optimizer "AdaptiveStochasticGradientDescent")
(Transform "EulerTransform")
(Interpolator "BSplineInterpolator")
(ResampleInterpolator "FinalBSplineInterpolator")
(Resampler "DefaultResampler")
(DefaultPixelValue 0)
